repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^backend/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/.*\.py$

  # General file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/.*\.py$
      - id: end-of-file-fixer
        files: ^backend/.*\.py$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        files: \.(json)$
      - id: check-toml
        files: \.(toml)$
